services:
  app:
    environment:
      SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${{ secrets.SPRING_DATASOURCE_DRIVER }}

      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_LOCATION: /home/ubuntu

    build:
      context: .
      dockerfile: ./dockerfile
    image: sojoo/sojoo:latest
    ports:
      - "80:80"
    depends_on:
      - redis
    volumes:
      - ./application-prod.yml:/home/ubuntu/compose/application-prod.yml

  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
