version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile-local
    image: myapp:local
    ports:
      - "8081:8081"
    depends_on:
      - redis
  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
#  controller:
#    image: ngrinder/controller:3.5.9
#    platform: linux/amd64
#    restart: always
#    ports:
#      - "9000:80"
#      - "16001:16001"
#      - "12000-12009:12000-12009"
#    volumes:
#      - /Applications/ngrinder-controller-3.5.9:/opt/ngrinder-controller
#  agent:
#    image: ngrinder/agent:3.5.9
#    platform: linux/amd64
#    restart: always
#    links:
#      - controller
