services:
  app:
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://rds-docker-server-storespotter.c52km662eg07.ap-northeast-2.rds.amazonaws.com:3306/storespotter_jpa
      SPRING_DATASOURCE_USERNAME: sojoo
      SPRING_DATASOURCE_PASSWORD: sojoo2024!
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sojoo/sojoo:latest
    ports:
      - "80:80"
    depends_on:
      - redis
  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
