services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sojoo/sojoo:latest
    ports:
      - '8080:8080'
    depends_on:
      - redis
    env_file:
      - ./.env

  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - '6379:6379'

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - /home/ubuntu/compose/conf/nginx:/etc/nginx/conf.d
      - /home/ubuntu/compose/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/compose/certbot/www:/var/www/certbot
    depends_on:
      - certbot

  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /home/ubuntu/compose/certbot/conf:/etc/letsencrypt
      - /home/ubuntu/compose/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

