services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sojoo/sojoo:latest
    ports:
      - "80:80"
    depends_on:
      - redis
  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
