services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sojoo/sojoo:latest
    ports:
      - '80:80'
    depends_on:
      - redis
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${SPRING_DATASOURCE_DRIVER}
      SPRING_MAIL_HOST: smtp.naver.com
      SPRING_MAIL_PORT: 465
      SPRING_MAIL_USERNAME: ${SMTP_USERNAME}
      SPRING_MAIL_PASSWORD: ${SMTP_PASSWORD}
      SPRING_MAIL_PROTOCAL: smtp
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: 123
      JWT_SECRET: ${JWT_SECRET_KEY}
      JWT_ACCESS_TOKEN_EXPIRDATION: 1800000
      JWT_REFRESH_TOKEN_EXPIEDATION: 2592000000
      API_NAVER_SERVICE_KEY: ${NAVER_SERVICE_KEY}

  redis:
    image: redis:latest
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    labels:
      - 'name=redis'
      - 'mode=standalone'
    ports:
      - '6379:6379'