server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8181
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://rds-docker-server-storespotter.c52km662eg07.ap-northeast-2.rds.amazonaws.com
    username: sojoo
    password: sojoo2024!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      show_sql: true
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  mail:
    host: smtp.naver.com
    port: 465
    username: techsupp@naver.com
    password: sojoo2024!
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessTokenExpiration: 1800000       # 30분
  refreshTokenExpiration: 2592000000   # 1달

  org.hibernate.SQL: debug

logging:
  level:
    root: debug
