server:
  servlet:
    encoding:
      charset: utf-8
      force: true

  port: 80
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  mail:
    host: smtp.naver.com
    port: 465
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true

jwt:
  header: Authorization
  secret: ${JWT_SECRET_KEY}
  accessTokenExpiration: 1800000       # 30분
  refreshTokenExpiration: 2592000000   # 1달

api:
  naverSerivceKey: ${NAVER_SERVICE_KEY}


logging:
  level:
    root: debug
