server:
  servlet:
    encoding:
      charset: utf-8
      force: true

  port: 80
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  mail:
    host: smtp.naver.com
    port: 465
    username: techsupp@naver.com
    password: sojoo2024!
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
      mail.smtp.ssl.trust: smtp.naver.com
      mail.smtp.starttls.enable: true

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  accessTokenExpiration: 1800000       # 30분
  refreshTokenExpiration: 2592000000   # 1달

api:
  naverSerivceKey: kXVB%2FzGPSXqZrn%2F1NuCYPZGJONAmxZfu%2BjQDCfDP%2F5uo8QZ%2B6iWdY%2FXrV%2B0gg2z%2BMKVEA%2BrVFLs9l0TVQE2Cug%3D%3D


logging:
  level:
    root: debug
