name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: make application-prod.yml
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.APPLICATION_PROD }}" > ./application-prod.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_USERNAME }}/sojoo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/sojoo:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ubuntu  # EC2 user
          key: ${{ secrets.AWS_EC2_PRIVATEKEY }} # pem 키
          # 도커 작업
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/sojoo:latest
            docker stop $(docker ps -a -q)
            docker run -d --log-driver=syslog -p 80:80 ${{ secrets.DOCKER_USERNAME }}/sojoo:latest
            docker rm $(docker ps --filter 'status=exited' -a -q)
            docker image prune -a -f
           docker-compose 작업
#          script: |
#            cd docker-compose.yml
#            docker-compose -f docker-compose.prod.yml pull
#            docker-compose -f docker-compose.prod.yml down # 기존 서비스 종료
#            docker-compose -f docker-compose.prod.yml up -d # 서비스 시작
